/* Automatically generated by create_config - do not modify */
#define TARGET_ABI_MIPSO32 1
#define TARGET_MIPS 1
#define TARGET_NAME "mips"
#define TARGET_MIPS 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
