/* Automatically generated by create_config - do not modify */
#define TARGET_RH850 1
#define TARGET_NAME "rh850"
#define TARGET_RH850 1
#define TARGET_SYSTBL_ABI common,nospu,64
#define CONFIG_SOFTMMU 1
