
/* Autogen header for Unicorn Engine - DONOT MODIFY */
#ifndef UNICORN_ARM__CPREG_H
#define UNICORN_ARM__CPREG_H

#define UC_ARM_CPREG_LIST \
	 UC_ARM_REG_ACTLR           , \
	 UC_ARM_REG_ACTLR2          , \
	 UC_ARM_REG_ADFSR           , \
	 UC_ARM_REG_AIDR            , \
	 UC_ARM_REG_AIFSR           , \
	 UC_ARM_REG_AMAIR0          , \
	 UC_ARM_REG_AMAIR1          , \
	 UC_ARM_REG_CCSIDR          , \
	 UC_ARM_REG_CCSIDR2         , \
	 UC_ARM_REG_CLIDR           , \
	 UC_ARM_REG_CNTFRQ          , \
	 UC_ARM_REG_CNTHCTL         , \
	 UC_ARM_REG_CNTHP_CTL       , \
	 UC_ARM_REG_CNTHP_CVAL      , \
	 UC_ARM_REG_CNTHP_TVAL      , \
	 UC_ARM_REG_CNTHV_CTL       , \
	 UC_ARM_REG_CNTHV_CVAL      , \
	 UC_ARM_REG_CNTHV_TVAL      , \
	 UC_ARM_REG_CNTKCTL         , \
	 UC_ARM_REG_CNTPCT          , \
	 UC_ARM_REG_CNTP_CTL        , \
	 UC_ARM_REG_CNTP_CVAL       , \
	 UC_ARM_REG_CNTP_TVAL       , \
	 UC_ARM_REG_CNTVCT          , \
	 UC_ARM_REG_CNTVOFF         , \
	 UC_ARM_REG_CNTV_CTL        , \
	 UC_ARM_REG_CNTV_CVAL       , \
	 UC_ARM_REG_CNTV_TVAL       , \
	 UC_ARM_REG_CONTEXTIDR      , \
	 UC_ARM_REG_CPACR           , \
	 UC_ARM_REG_CSSELR          , \
	 UC_ARM_REG_CTR             , \
	 UC_ARM_REG_DACR            , \
	 UC_ARM_REG_DBGAUTHSTATUS   , \
	 UC_ARM_REG_DBGBCR0         , \
	 UC_ARM_REG_DBGBCR1         , \
	 UC_ARM_REG_DBGBCR2         , \
	 UC_ARM_REG_DBGBCR3         , \
	 UC_ARM_REG_DBGBCR4         , \
	 UC_ARM_REG_DBGBCR5         , \
	 UC_ARM_REG_DBGBCR6         , \
	 UC_ARM_REG_DBGBCR7         , \
	 UC_ARM_REG_DBGBCR8         , \
	 UC_ARM_REG_DBGBCR9         , \
	 UC_ARM_REG_DBGBCR10        , \
	 UC_ARM_REG_DBGBCR11        , \
	 UC_ARM_REG_DBGBCR12        , \
	 UC_ARM_REG_DBGBCR13        , \
	 UC_ARM_REG_DBGBCR14        , \
	 UC_ARM_REG_DBGBVR0         , \
	 UC_ARM_REG_DBGBVR1         , \
	 UC_ARM_REG_DBGBVR2         , \
	 UC_ARM_REG_DBGBVR3         , \
	 UC_ARM_REG_DBGBVR4         , \
	 UC_ARM_REG_DBGBVR5         , \
	 UC_ARM_REG_DBGBVR6         , \
	 UC_ARM_REG_DBGBVR7         , \
	 UC_ARM_REG_DBGBVR8         , \
	 UC_ARM_REG_DBGBVR9         , \
	 UC_ARM_REG_DBGBVR10        , \
	 UC_ARM_REG_DBGBVR11        , \
	 UC_ARM_REG_DBGBVR12        , \
	 UC_ARM_REG_DBGBVR13        , \
	 UC_ARM_REG_DBGBVR14        , \
	 UC_ARM_REG_DBGBXVR0        , \
	 UC_ARM_REG_DBGBXVR1        , \
	 UC_ARM_REG_DBGBXVR2        , \
	 UC_ARM_REG_DBGBXVR3        , \
	 UC_ARM_REG_DBGBXVR4        , \
	 UC_ARM_REG_DBGBXVR5        , \
	 UC_ARM_REG_DBGBXVR6        , \
	 UC_ARM_REG_DBGBXVR7        , \
	 UC_ARM_REG_DBGBXVR8        , \
	 UC_ARM_REG_DBGBXVR9        , \
	 UC_ARM_REG_DBGBXVR10       , \
	 UC_ARM_REG_DBGBXVR11       , \
	 UC_ARM_REG_DBGBXVR12       , \
	 UC_ARM_REG_DBGBXVR13       , \
	 UC_ARM_REG_DBGBXVR14       , \
	 UC_ARM_REG_DBGCLAIMCLR     , \
	 UC_ARM_REG_DBGCLAIMSET     , \
	 UC_ARM_REG_DBGDCCINT       , \
	 UC_ARM_REG_DBGDEVID        , \
	 UC_ARM_REG_DBGDEVID1       , \
	 UC_ARM_REG_DBGDEVID2       , \
	 UC_ARM_REG_DBGDIDR         , \
	 UC_ARM_REG_DBGDRAR         , \
	 UC_ARM_REG_DBGDSAR         , \
	 UC_ARM_REG_DBGDSCRext      , \
	 UC_ARM_REG_DBGDSCRint      , \
	 UC_ARM_REG_DBGDTRRXext     , \
	 UC_ARM_REG_DBGDTRRXint     , \
	 UC_ARM_REG_DBGDTRTXext     , \
	 UC_ARM_REG_DBGDTRTXint     , \
	 UC_ARM_REG_DBGOSDLR        , \
	 UC_ARM_REG_DBGOSECCR       , \
	 UC_ARM_REG_DBGOSLAR        , \
	 UC_ARM_REG_DBGOSLSR        , \
	 UC_ARM_REG_DBGPRCR         , \
	 UC_ARM_REG_DBGVCR          , \
	 UC_ARM_REG_DBGWCR0         , \
	 UC_ARM_REG_DBGWCR1         , \
	 UC_ARM_REG_DBGWCR2         , \
	 UC_ARM_REG_DBGWCR3         , \
	 UC_ARM_REG_DBGWCR4         , \
	 UC_ARM_REG_DBGWCR5         , \
	 UC_ARM_REG_DBGWCR6         , \
	 UC_ARM_REG_DBGWCR7         , \
	 UC_ARM_REG_DBGWCR8         , \
	 UC_ARM_REG_DBGWCR9         , \
	 UC_ARM_REG_DBGWCR10        , \
	 UC_ARM_REG_DBGWCR11        , \
	 UC_ARM_REG_DBGWCR12        , \
	 UC_ARM_REG_DBGWCR13        , \
	 UC_ARM_REG_DBGWCR14        , \
	 UC_ARM_REG_DBGWFAR         , \
	 UC_ARM_REG_DBGWVR0         , \
	 UC_ARM_REG_DBGWVR1         , \
	 UC_ARM_REG_DBGWVR2         , \
	 UC_ARM_REG_DBGWVR3         , \
	 UC_ARM_REG_DBGWVR4         , \
	 UC_ARM_REG_DBGWVR5         , \
	 UC_ARM_REG_DBGWVR6         , \
	 UC_ARM_REG_DBGWVR7         , \
	 UC_ARM_REG_DBGWVR8         , \
	 UC_ARM_REG_DBGWVR9         , \
	 UC_ARM_REG_DBGWVR10        , \
	 UC_ARM_REG_DBGWVR11        , \
	 UC_ARM_REG_DBGWVR12        , \
	 UC_ARM_REG_DBGWVR13        , \
	 UC_ARM_REG_DBGWVR14        , \
	 UC_ARM_REG_DFAR            , \
	 UC_ARM_REG_DFSR            , \
	 UC_ARM_REG_DLR             , \
	 UC_ARM_REG_DSPSR           , \
	 UC_ARM_REG_FCSEIDR         , \
	 UC_ARM_REG_HACR            , \
	 UC_ARM_REG_HACTLR          , \
	 UC_ARM_REG_HACTLR2         , \
	 UC_ARM_REG_HADFSR          , \
	 UC_ARM_REG_HAIFSR          , \
	 UC_ARM_REG_HAMAIR0         , \
	 UC_ARM_REG_HAMAIR1         , \
	 UC_ARM_REG_HCPTR           , \
	 UC_ARM_REG_HCR             , \
	 UC_ARM_REG_HCR2            , \
	 UC_ARM_REG_HDCR            , \
	 UC_ARM_REG_HDFAR           , \
	 UC_ARM_REG_HIFAR           , \
	 UC_ARM_REG_HMAIR0          , \
	 UC_ARM_REG_HMAIR1          , \
	 UC_ARM_REG_HPFAR           , \
	 UC_ARM_REG_HRMR            , \
	 UC_ARM_REG_HSCTLR          , \
	 UC_ARM_REG_HSR             , \
	 UC_ARM_REG_HSTR            , \
	 UC_ARM_REG_HTCR            , \
	 UC_ARM_REG_HTPIDR          , \
	 UC_ARM_REG_HTTBR           , \
	 UC_ARM_REG_HVBAR           , \
	 UC_ARM_REG_ICC_AP0R0       , \
	 UC_ARM_REG_ICC_AP0R1       , \
	 UC_ARM_REG_ICC_AP0R2       , \
	 UC_ARM_REG_ICC_AP1R0       , \
	 UC_ARM_REG_ICC_AP1R1       , \
	 UC_ARM_REG_ICC_AP1R2       , \
	 UC_ARM_REG_ICC_ASGI1R      , \
	 UC_ARM_REG_ICC_BPR0        , \
	 UC_ARM_REG_ICC_BPR1        , \
	 UC_ARM_REG_ICC_CTLR        , \
	 UC_ARM_REG_ICC_DIR         , \
	 UC_ARM_REG_ICC_EOIR0       , \
	 UC_ARM_REG_ICC_EOIR1       , \
	 UC_ARM_REG_ICC_HPPIR0      , \
	 UC_ARM_REG_ICC_HPPIR1      , \
	 UC_ARM_REG_ICC_HSRE        , \
	 UC_ARM_REG_ICC_IAR0        , \
	 UC_ARM_REG_ICC_IAR1        , \
	 UC_ARM_REG_ICC_IGRPEN0     , \
	 UC_ARM_REG_ICC_IGRPEN1     , \
	 UC_ARM_REG_ICC_MCTLR       , \
	 UC_ARM_REG_ICC_MGRPEN1     , \
	 UC_ARM_REG_ICC_MSRE        , \
	 UC_ARM_REG_ICC_PMR         , \
	 UC_ARM_REG_ICC_RPR         , \
	 UC_ARM_REG_ICC_SGI0R       , \
	 UC_ARM_REG_ICC_SGI1R       , \
	 UC_ARM_REG_ICC_SRE         , \
	 UC_ARM_REG_ICH_AP0R0       , \
	 UC_ARM_REG_ICH_AP0R1       , \
	 UC_ARM_REG_ICH_AP0R2       , \
	 UC_ARM_REG_ICH_AP1R0       , \
	 UC_ARM_REG_ICH_AP1R1       , \
	 UC_ARM_REG_ICH_AP1R2       , \
	 UC_ARM_REG_ICH_EISR        , \
	 UC_ARM_REG_ICH_ELRSR       , \
	 UC_ARM_REG_ICH_HCR         , \
	 UC_ARM_REG_ICH_LR0         , \
	 UC_ARM_REG_ICH_LR1         , \
	 UC_ARM_REG_ICH_LR2         , \
	 UC_ARM_REG_ICH_LR3         , \
	 UC_ARM_REG_ICH_LR4         , \
	 UC_ARM_REG_ICH_LR5         , \
	 UC_ARM_REG_ICH_LR6         , \
	 UC_ARM_REG_ICH_LR7         , \
	 UC_ARM_REG_ICH_LR8         , \
	 UC_ARM_REG_ICH_LR9         , \
	 UC_ARM_REG_ICH_LR10        , \
	 UC_ARM_REG_ICH_LR11        , \
	 UC_ARM_REG_ICH_LR12        , \
	 UC_ARM_REG_ICH_LR13        , \
	 UC_ARM_REG_ICH_LR14        , \
	 UC_ARM_REG_ICH_LRC0        , \
	 UC_ARM_REG_ICH_LRC1        , \
	 UC_ARM_REG_ICH_LRC2        , \
	 UC_ARM_REG_ICH_LRC3        , \
	 UC_ARM_REG_ICH_LRC4        , \
	 UC_ARM_REG_ICH_LRC5        , \
	 UC_ARM_REG_ICH_LRC6        , \
	 UC_ARM_REG_ICH_LRC7        , \
	 UC_ARM_REG_ICH_LRC8        , \
	 UC_ARM_REG_ICH_LRC9        , \
	 UC_ARM_REG_ICH_LRC10       , \
	 UC_ARM_REG_ICH_LRC11       , \
	 UC_ARM_REG_ICH_LRC12       , \
	 UC_ARM_REG_ICH_LRC13       , \
	 UC_ARM_REG_ICH_LRC14       , \
	 UC_ARM_REG_ICH_MISR        , \
	 UC_ARM_REG_ICH_VMCR        , \
	 UC_ARM_REG_ICH_VTR         , \
	 UC_ARM_REG_ICV_AP0R0       , \
	 UC_ARM_REG_ICV_AP0R1       , \
	 UC_ARM_REG_ICV_AP0R2       , \
	 UC_ARM_REG_ICV_AP1R0       , \
	 UC_ARM_REG_ICV_AP1R1       , \
	 UC_ARM_REG_ICV_AP1R2       , \
	 UC_ARM_REG_ICV_BPR0        , \
	 UC_ARM_REG_ICV_BPR1        , \
	 UC_ARM_REG_ICV_CTLR        , \
	 UC_ARM_REG_ICV_DIR         , \
	 UC_ARM_REG_ICV_EOIR0       , \
	 UC_ARM_REG_ICV_EOIR1       , \
	 UC_ARM_REG_ICV_HPPIR0      , \
	 UC_ARM_REG_ICV_HPPIR1      , \
	 UC_ARM_REG_ICV_IAR0        , \
	 UC_ARM_REG_ICV_IAR1        , \
	 UC_ARM_REG_ICV_IGRPEN0     , \
	 UC_ARM_REG_ICV_IGRPEN1     , \
	 UC_ARM_REG_ICV_PMR         , \
	 UC_ARM_REG_ICV_RPR         , \
	 UC_ARM_REG_ID_AFR0         , \
	 UC_ARM_REG_ID_DFR0         , \
	 UC_ARM_REG_ID_ISAR0        , \
	 UC_ARM_REG_ID_ISAR1        , \
	 UC_ARM_REG_ID_ISAR2        , \
	 UC_ARM_REG_ID_ISAR3        , \
	 UC_ARM_REG_ID_ISAR4        , \
	 UC_ARM_REG_ID_ISAR5        , \
	 UC_ARM_REG_ID_ISAR6        , \
	 UC_ARM_REG_ID_MMFR0        , \
	 UC_ARM_REG_ID_MMFR1        , \
	 UC_ARM_REG_ID_MMFR2        , \
	 UC_ARM_REG_ID_MMFR3        , \
	 UC_ARM_REG_ID_MMFR4        , \
	 UC_ARM_REG_ID_PFR0         , \
	 UC_ARM_REG_ID_PFR1         , \
	 UC_ARM_REG_IFAR            , \
	 UC_ARM_REG_IFSR            , \
	 UC_ARM_REG_ISR             , \
	 UC_ARM_REG_JIDR            , \
	 UC_ARM_REG_JMCR            , \
	 UC_ARM_REG_JOSCR           , \
	 UC_ARM_REG_MAIR0           , \
	 UC_ARM_REG_MAIR1           , \
	 UC_ARM_REG_MIDR            , \
	 UC_ARM_REG_MPIDR           , \
	 UC_ARM_REG_MVBAR           , \
	 UC_ARM_REG_NMRR            , \
	 UC_ARM_REG_NSACR           , \
	 UC_ARM_REG_PAR             , \
	 UC_ARM_REG_PMCCFILTR       , \
	 UC_ARM_REG_PMCCNTR         , \
	 UC_ARM_REG_PMCEID0         , \
	 UC_ARM_REG_PMCEID1         , \
	 UC_ARM_REG_PMCEID2         , \
	 UC_ARM_REG_PMCEID3         , \
	 UC_ARM_REG_PMCNTENCLR      , \
	 UC_ARM_REG_PMCNTENSET      , \
	 UC_ARM_REG_PMCR            , \
	 UC_ARM_REG_PMEVCNTR0       , \
	 UC_ARM_REG_PMEVCNTR1       , \
	 UC_ARM_REG_PMEVCNTR2       , \
	 UC_ARM_REG_PMEVCNTR3       , \
	 UC_ARM_REG_PMEVCNTR4       , \
	 UC_ARM_REG_PMEVCNTR5       , \
	 UC_ARM_REG_PMEVCNTR6       , \
	 UC_ARM_REG_PMEVCNTR7       , \
	 UC_ARM_REG_PMEVCNTR8       , \
	 UC_ARM_REG_PMEVCNTR9       , \
	 UC_ARM_REG_PMEVCNTR10      , \
	 UC_ARM_REG_PMEVCNTR11      , \
	 UC_ARM_REG_PMEVCNTR12      , \
	 UC_ARM_REG_PMEVCNTR13      , \
	 UC_ARM_REG_PMEVCNTR14      , \
	 UC_ARM_REG_PMEVCNTR15      , \
	 UC_ARM_REG_PMEVCNTR16      , \
	 UC_ARM_REG_PMEVCNTR17      , \
	 UC_ARM_REG_PMEVCNTR18      , \
	 UC_ARM_REG_PMEVCNTR19      , \
	 UC_ARM_REG_PMEVCNTR20      , \
	 UC_ARM_REG_PMEVCNTR21      , \
	 UC_ARM_REG_PMEVCNTR22      , \
	 UC_ARM_REG_PMEVCNTR23      , \
	 UC_ARM_REG_PMEVCNTR24      , \
	 UC_ARM_REG_PMEVCNTR25      , \
	 UC_ARM_REG_PMEVCNTR26      , \
	 UC_ARM_REG_PMEVCNTR27      , \
	 UC_ARM_REG_PMEVCNTR28      , \
	 UC_ARM_REG_PMEVCNTR29      , \
	 UC_ARM_REG_PMEVTYPER0      , \
	 UC_ARM_REG_PMEVTYPER1      , \
	 UC_ARM_REG_PMEVTYPER2      , \
	 UC_ARM_REG_PMEVTYPER3      , \
	 UC_ARM_REG_PMEVTYPER4      , \
	 UC_ARM_REG_PMEVTYPER5      , \
	 UC_ARM_REG_PMEVTYPER6      , \
	 UC_ARM_REG_PMEVTYPER7      , \
	 UC_ARM_REG_PMEVTYPER8      , \
	 UC_ARM_REG_PMEVTYPER9      , \
	 UC_ARM_REG_PMEVTYPER10     , \
	 UC_ARM_REG_PMEVTYPER11     , \
	 UC_ARM_REG_PMEVTYPER12     , \
	 UC_ARM_REG_PMEVTYPER13     , \
	 UC_ARM_REG_PMEVTYPER14     , \
	 UC_ARM_REG_PMEVTYPER15     , \
	 UC_ARM_REG_PMEVTYPER16     , \
	 UC_ARM_REG_PMEVTYPER17     , \
	 UC_ARM_REG_PMEVTYPER18     , \
	 UC_ARM_REG_PMEVTYPER19     , \
	 UC_ARM_REG_PMEVTYPER20     , \
	 UC_ARM_REG_PMEVTYPER21     , \
	 UC_ARM_REG_PMEVTYPER22     , \
	 UC_ARM_REG_PMEVTYPER23     , \
	 UC_ARM_REG_PMEVTYPER24     , \
	 UC_ARM_REG_PMEVTYPER25     , \
	 UC_ARM_REG_PMEVTYPER26     , \
	 UC_ARM_REG_PMEVTYPER27     , \
	 UC_ARM_REG_PMEVTYPER28     , \
	 UC_ARM_REG_PMEVTYPER29     , \
	 UC_ARM_REG_PMINTENCLR      , \
	 UC_ARM_REG_PMINTENSET      , \
	 UC_ARM_REG_PMOVSR          , \
	 UC_ARM_REG_PMOVSSET        , \
	 UC_ARM_REG_PMSELR          , \
	 UC_ARM_REG_PMSWINC         , \
	 UC_ARM_REG_PMUSERENR       , \
	 UC_ARM_REG_PMXEVCNTR       , \
	 UC_ARM_REG_PMXEVTYPER      , \
	 UC_ARM_REG_PRRR            , \
	 UC_ARM_REG_REVIDR          , \
	 UC_ARM_REG_RMR             , \
	 UC_ARM_REG_RVBAR           , \
	 UC_ARM_REG_SCR             , \
	 UC_ARM_REG_SCTLR           , \
	 UC_ARM_REG_SDCR            , \
	 UC_ARM_REG_SDER            , \
	 UC_ARM_REG_TCMTR           , \
	 UC_ARM_REG_TLBTR           , \
	 UC_ARM_REG_TPIDRPRW        , \
	 UC_ARM_REG_TPIDRURO        , \
	 UC_ARM_REG_TPIDRURW        , \
	 UC_ARM_REG_TTBCR           , \
	 UC_ARM_REG_TTBCR2          , \
	 UC_ARM_REG_TTBR0           , \
	 UC_ARM_REG_TTBR1           , \
	 UC_ARM_REG_VBAR            , \
	 UC_ARM_REG_VMPIDR          , \
	 UC_ARM_REG_VPIDR           , \
	 UC_ARM_REG_VTCR            , \
	 UC_ARM_REG_VTTBR           , \


#endif