obj-y += cpu-models.o
ifeq ($(CONFIG_SOFTMMU),y)
obj-y += mmu_helper.o mmu-hash32.o
obj-$(TARGET_PPC64) += mmu-hash64.o
endif
obj-y += dfp_helper.o
obj-y += excp_helper.o
obj-y += fpu_helper.o
obj-y += int_helper.o
obj-y += timebase_helper.o
obj-y += misc_helper.o
obj-y += mem_helper.o
obj-$(CONFIG_USER_ONLY) += user_only_helper.o
#obj-y += gdbstub.o
obj-y += translate.o
obj-y += unicorn.o

